# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TabBar_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'JXSegmentedView'
pod 'JXPagingView/Paging'

pod 'SnapKit', '5.0.1'
pod 'SwiftyJSON'

  # Pods for TabBar_Swift

end
